[[constraint]]
  name = "github.com/chzyer/readline"
  version = "1.4.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"
